// <auto-generated />
using System;
using HomeWork28._05;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeWork28._05.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("HomeWork28._05.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Master Ugvey",
                            InsertDate = new DateTime(2012, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Случайности не случайные"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Master Ugvey",
                            InsertDate = new DateTime(2013, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Случайности не случайные"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Master Ugvey",
                            InsertDate = new DateTime(2014, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Случайности не случайные"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Master Ugvey",
                            InsertDate = new DateTime(2015, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Случайности не случайные"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Master Ugvey",
                            InsertDate = new DateTime(2016, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Случайности не случайные"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
